# This is a basic workflow to help you get started with Actions

name: Backup the Github organization repos to Gitee.
on: [push, pull_request]
 # schedule:
 #   - cron:  '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Backup code at github to gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/IHEP-LQCD
          dst: gitee/IHEP-LQCD
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: org
